### PR TITLE
Fix for STI classes, fixes #89

### LINKED ISSUE #89: self.class.after_commit_counter_cache is nil when calling update from controller
I'm getting an error when calling update_attributes for an api I'm writing. It's working from the console, but it's not working through the api controller.
```
NoMethodError:
       undefined method `each' for nil:NilClass
```

Here's the full stack trace:

```
counter_culture (0.1.27) lib/counter_culture.rb:249:in `block in _update_counts_after_update&#39;
counter_culture (0.1.27) lib/counter_culture.rb:221:in `call&#39;
counter_culture (0.1.27) lib/counter_culture.rb:221:in `_wrap_in_counter_culture_active&#39;
counter_culture (0.1.27) lib/counter_culture.rb:248:in `_update_counts_after_update&#39;
activesupport (4.1.2) lib/active_support/callbacks.rb:424:in `block in make_lambda&#39;
activesupport (4.1.2) lib/active_support/callbacks.rb:221:in `call&#39;
activesupport (4.1.2) lib/active_support/callbacks.rb:221:in `block in halting_and_conditional&#39;
activesupport (4.1.2) lib/active_support/callbacks.rb:86:in `call&#39;
activesupport (4.1.2) lib/active_support/callbacks.rb:86:in `run_callbacks&#39;
activerecord (4.1.2) lib/active_record/callbacks.rb:310:in `_update_record&#39;
activerecord (4.1.2) lib/active_record/timestamp.rb:70:in `_update_record&#39;
activerecord (4.1.2) lib/active_record/persistence.rb:482:in `create_or_update&#39;
activerecord (4.1.2) lib/active_record/callbacks.rb:302:in `block in create_or_update&#39;
activesupport (4.1.2) lib/active_support/callbacks.rb:113:in `call&#39;
activesupport (4.1.2) lib/active_support/callbacks.rb:113:in `call&#39;
activesupport (4.1.2) lib/active_support/callbacks.rb:166:in `block in halting&#39;
activesupport (4.1.2) lib/active_support/callbacks.rb:166:in `call&#39;
activesupport (4.1.2) lib/active_support/callbacks.rb:166:in `block in halting&#39;
activesupport (4.1.2) lib/active_support/callbacks.rb:86:in `call&#39;
activesupport (4.1.2) lib/active_support/callbacks.rb:86:in `run_callbacks&#39;
activerecord (4.1.2) lib/active_record/callbacks.rb:302:in `create_or_update&#39;
activerecord (4.1.2) lib/active_record/persistence.rb:103:in `save&#39;
activerecord (4.1.2) lib/active_record/validations.rb:51:in `save&#39;
activerecord (4.1.2) lib/active_record/attribute_methods/dirty.rb:21:in `save&#39;
activerecord (4.1.2) lib/active_record/transactions.rb:268:in `block (2 levels) in save&#39;
activerecord (4.1.2) lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status&#39;
activerecord (4.1.2) lib/active_record/connection_adapters/abstract/database_statements.rb:199:in `transaction&#39;
activerecord (4.1.2) lib/active_record/transactions.rb:208:in `transaction&#39;
activerecord (4.1.2) lib/active_record/transactions.rb:326:in `with_transaction_returning_status&#39;
activerecord (4.1.2) lib/active_record/transactions.rb:268:in `block in save&#39;
activerecord (4.1.2) lib/active_record/transactions.rb:283:in `rollback_active_record_state!&#39;
activerecord (4.1.2) lib/active_record/transactions.rb:267:in `save&#39;
activerecord (4.1.2) lib/active_record/persistence.rb:232:in `block in update&#39;
activerecord (4.1.2) lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status&#39;
activerecord (4.1.2) lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction&#39;
activerecord (4.1.2) lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction&#39;
activerecord (4.1.2) lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction&#39;
activerecord (4.1.2) lib/active_record/transactions.rb:208:in `transaction&#39;
activerecord (4.1.2) lib/active_record/transactions.rb:326:in `with_transaction_returning_status&#39;
activerecord (4.1.2) lib/active_record/persistence.rb:230:in `update&#39;
actionpack (4.1.2) lib/action_controller/metal/implicit_render.rb:4:in `send_action&#39;
actionpack (4.1.2) lib/abstract_controller/base.rb:189:in `process_action&#39;
actionpack (4.1.2) lib/action_controller/metal/rendering.rb:10:in `process_action&#39;
actionpack (4.1.2) lib/abstract_controller/callbacks.rb:20:in `block in process_action&#39;
activesupport (4.1.2) lib/active_support/callbacks.rb:113:in `call&#39;
activesupport (4.1.2) lib/active_support/callbacks.rb:113:in `call&#39;
activesupport (4.1.2) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional&#39;
activesupport (4.1.2) lib/active_support/callbacks.rb:166:in `call&#39;
activesupport (4.1.2) lib/active_support/callbacks.rb:166:in `block in halting&#39;
activesupport (4.1.2) lib/active_support/callbacks.rb:229:in `call&#39;
activesupport (4.1.2) lib/active_support/callbacks.rb:229:in `block in halting&#39;
activesupport (4.1.2) lib/active_support/callbacks.rb:166:in `call&#39;
activesupport (4.1.2) lib/active_support/callbacks.rb:166:in `block in halting&#39;
activesupport (4.1.2) lib/active_support/callbacks.rb:86:in `call&#39;
activesupport (4.1.2) lib/active_support/callbacks.rb:86:in `run_callbacks&#39;
actionpack (4.1.2) lib/abstract_controller/callbacks.rb:19:in `process_action&#39;
actionpack (4.1.2) lib/action_controller/metal/rescue.rb:29:in `process_action&#39;
actionpack (4.1.2) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action&#39;
activesupport (4.1.2) lib/active_support/notifications.rb:159:in `block in instrument&#39;
activesupport (4.1.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument&#39;
activesupport (4.1.2) lib/active_support/notifications.rb:159:in `instrument&#39;
actionpack (4.1.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action&#39;
actionpack (4.1.2) lib/action_controller/metal/params_wrapper.rb:250:in `process_action&#39;
activerecord (4.1.2) lib/active_record/railties/controller_runtime.rb:18:in `process_action&#39;
actionpack (4.1.2) lib/abstract_controller/base.rb:136:in `process&#39;
actionview (4.1.2) lib/action_view/rendering.rb:30:in `process&#39;
rack-mini-profiler (0.9.2) lib/mini_profiler/profiling_methods.rb:108:in `block in profile_method&#39;
actionpack (4.1.2) lib/action_controller/metal.rb:196:in `dispatch&#39;
actionpack (4.1.2) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch&#39;
actionpack (4.1.2) lib/action_controller/metal.rb:232:in `block in action&#39;
actionpack (4.1.2) lib/action_dispatch/routing/route_set.rb:82:in `call&#39;
actionpack (4.1.2) lib/action_dispatch/routing/route_set.rb:82:in `dispatch&#39;
actionpack (4.1.2) lib/action_dispatch/routing/route_set.rb:50:in `call&#39;
actionpack (4.1.2) lib/action_dispatch/journey/router.rb:71:in `block in call&#39;
actionpack (4.1.2) lib/action_dispatch/journey/router.rb:59:in `each&#39;
actionpack (4.1.2) lib/action_dispatch/journey/router.rb:59:in `call&#39;
actionpack (4.1.2) lib/action_dispatch/routing/route_set.rb:678:in `call&#39;
newrelic_rpm (3.9.7.266) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call&#39;
newrelic_rpm (3.9.7.266) lib/new_relic/rack/agent_hooks.rb:26:in `traced_call&#39;
newrelic_rpm (3.9.7.266) lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call&#39;
newrelic_rpm (3.9.7.266) lib/new_relic/rack/browser_monitoring.rb:23:in `traced_call&#39;
newrelic_rpm (3.9.7.266) lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call&#39;
newrelic_rpm (3.9.7.266) lib/new_relic/rack/developer_mode.rb:56:in `traced_call&#39;
newrelic_rpm (3.9.7.266) lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call&#39;
rack (1.5.2) lib/rack/etag.rb:23:in `call&#39;
newrelic_rpm (3.9.7.266) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call&#39;
rack (1.5.2) lib/rack/conditionalget.rb:35:in `call&#39;
newrelic_rpm (3.9.7.266) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call&#39;
rack (1.5.2) lib/rack/head.rb:11:in `call&#39;
newrelic_rpm (3.9.7.266) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call&#39;
actionpack (4.1.2) lib/action_dispatch/middleware/params_parser.rb:27:in `call&#39;
newrelic_rpm (3.9.7.266) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call&#39;
actionpack (4.1.2) lib/action_dispatch/middleware/flash.rb:254:in `call&#39;
newrelic_rpm (3.9.7.266) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call&#39;
rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context&#39;
rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call&#39;
newrelic_rpm (3.9.7.266) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call&#39;
actionpack (4.1.2) lib/action_dispatch/middleware/cookies.rb:560:in `call&#39;
newrelic_rpm (3.9.7.266) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call&#39;
activerecord (4.1.2) lib/active_record/query_cache.rb:36:in `call&#39;
newrelic_rpm (3.9.7.266) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call&#39;
activerecord (4.1.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call&#39;
newrelic_rpm (3.9.7.266) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call&#39;
activerecord (4.1.2) lib/active_record/migration.rb:380:in `call&#39;
newrelic_rpm (3.9.7.266) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call&#39;
actionpack (4.1.2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call&#39;
activesupport (4.1.2) lib/active_support/callbacks.rb:82:in `run_callbacks&#39;
actionpack (4.1.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call&#39;
newrelic_rpm (3.9.7.266) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call&#39;
actionpack (4.1.2) lib/action_dispatch/middleware/reloader.rb:73:in `call&#39;
newrelic_rpm (3.9.7.266) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call&#39;
actionpack (4.1.2) lib/action_dispatch/middleware/remote_ip.rb:76:in `call&#39;
newrelic_rpm (3.9.7.266) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call&#39;
actionpack (4.1.2) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call&#39;
newrelic_rpm (3.9.7.266) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call&#39;
actionpack (4.1.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call&#39;
newrelic_rpm (3.9.7.266) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call&#39;
railties (4.1.2) lib/rails/rack/logger.rb:38:in `call_app&#39;
railties (4.1.2) lib/rails/rack/logger.rb:20:in `block in call&#39;
activesupport (4.1.2) lib/active_support/tagged_logging.rb:68:in `block in tagged&#39;
activesupport (4.1.2) lib/active_support/tagged_logging.rb:26:in `tagged&#39;
activesupport (4.1.2) lib/active_support/tagged_logging.rb:68:in `tagged&#39;
railties (4.1.2) lib/rails/rack/logger.rb:20:in `call&#39;
newrelic_rpm (3.9.7.266) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call&#39;
actionpack (4.1.2) lib/action_dispatch/middleware/request_id.rb:21:in `call&#39;
newrelic_rpm (3.9.7.266) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call&#39;
rack (1.5.2) lib/rack/methodoverride.rb:21:in `call&#39;
newrelic_rpm (3.9.7.266) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call&#39;
rack (1.5.2) lib/rack/runtime.rb:17:in `call&#39;
newrelic_rpm (3.9.7.266) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call&#39;
activesupport (4.1.2) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call&#39;
newrelic_rpm (3.9.7.266) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call&#39;
rack (1.5.2) lib/rack/lock.rb:17:in `call&#39;
newrelic_rpm (3.9.7.266) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call&#39;
actionpack (4.1.2) lib/action_dispatch/middleware/static.rb:64:in `call&#39;
newrelic_rpm (3.9.7.266) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call&#39;
rack (1.5.2) lib/rack/sendfile.rb:112:in `call&#39;
newrelic_rpm (3.9.7.266) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call&#39;
rack-mini-profiler (0.9.2) lib/mini_profiler/profiler.rb:300:in `call&#39;
newrelic_rpm (3.9.7.266) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call&#39;
railties (4.1.2) lib/rails/engine.rb:514:in `call&#39;
railties (4.1.2) lib/rails/application.rb:144:in `call&#39;
newrelic_rpm (3.9.7.266) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call&#39;
rack (1.5.2) lib/rack/lock.rb:17:in `call&#39;
rack (1.5.2) lib/rack/content_length.rb:14:in `call&#39;
rack (1.5.2) lib/rack/handler/webrick.rb:60:in `service&#39;
/Users/josh/.rbenv/versions/2.1.3/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service&#39;
/Users/josh/.rbenv/versions/2.1.3/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run&#39;
/Users/josh/.rbenv/versions/2.1.3/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread&#39;
```

Here's what my code looks like:

```
#update method from the controller
 def update
        @domain.update_attributes(domain_params)
end

class ErrorDomain < ActiveRecord::Base
counter_culture [:seed_url, :backlink_seed], 
		column_name: Proc.new {|error_domain| error_domain.available_da? ? 'available_da_count' : nil},
		column_names: {
			['error_domains.available = ? AND error_domains.moz_da > ?', true, 15] => 'available_da_count'
		}

	counter_culture [:seed_url, :backlink_seed], 
		column_name: Proc.new {|error_domain| error_domain.spam_free? ? 'spam_free_count' : nil},
		column_names: {
			["error_domains." + 
				FULL_DATA_COLUMNS.join(" IS NOT NULL AND error_domains.") + " IS NOT NULL" + 
				" AND error_domains.anchor_spam_status IN (?) AND spam_backlinks_count > 0", SPAM_FREE_ANCHOR_STATUSES] => 'spam_free_count'
		}
	counter_culture :seed_url, 
		column_name: Proc.new {|error_domain| error_domain.available_da? ? 'available_da_count' : nil},
		column_names: {
			['error_domains.available = ? AND error_domains.moz_da > ?', true, 15] => 'available_da_count'
		}

	counter_culture :seed_url, 
		column_name: Proc.new {|error_domain| error_domain.spam_free? ? 'spam_free_count' : nil},
		column_names: {
			["error_domains." + 
				FULL_DATA_COLUMNS.join(" IS NOT NULL AND error_domains.") + " IS NOT NULL" + 
				" AND error_domains.anchor_spam_status IN (?) AND spam_backlinks_count > 0", SPAM_FREE_ANCHOR_STATUSES] => 'spam_free_count'
		}
end
```

Apologies for the code dump, but I don't really have an idea what would be causing this. Counter_culture has been working just fine interacting with it from other controllers and background tasks. But it seems to have issues when I'm working with it from the api controller. 

Any chance someone could point me in the right direction? 

Thanks!

### PR DESCRIPTION
**Pull request by magnusvk**

### CODE REVIEW

File: lib/counter_culture.rb [hunk 1]
```diff
@@ -13,7 +13,13 @@ module ActiveRecord
...
     module ClassMethods
       # this holds all configuration data
-      attr_reader :after_commit_counter_cache
+      def after_commit_counter_cache
+        config = @after_commit_counter_cache
+        if !config && superclass.respond_to?(:after_commit_counter_cache)
+          config = superclass.after_commit_counter_cache
+        end
+        config
+      end
```
Comment (mockdeep) [inline lib/counter_culture.rb]: Does this work when there is a counter cache both on the super-class and the sub-class? It looks to me like the sub-class config might clobber the super-class config.

File: spec/counter_culture_spec.rb [hunk 2]
```diff
@@ -945,6 +946,14 @@
     product.twitter_reviews_count.should == 1
   end
 
+  it "handles an inherited STI counter cache correctly", focus: true do
```
Comment (mockdeep) [inline spec/counter_culture_spec.rb]: If you remove the `focus: true` here you could keep the config in `spec_helper` for your convenience. That way you can focus any spec you're working on.

**Comment by mockdeep** [comment]
Thanks for such a quick turnaround, btw.

File: lib/counter_culture.rb (hunk 1 above)
Comment (mockdeep) [inline lib/counter_culture.rb]: It actually looks like it might be a use case for the much-maligned `@@` variable, though who knows what other horrible side effects that might have...

Comment (magnusvk) [inline lib/counter_culture.rb]: Yeah, the sub-class config _would_ clobber the superclass. But it's not 100% clear to me what the correct behavior should actually be.

I agree that `@@` might be the way to go. I tried that route, unfortunately I couldn't get it to work. I think I'll give that another shot, though, as it really seems to be what I'm looking for here.

Comment (mockdeep) [inline lib/counter_culture.rb]: It seems to me like you'd want to preserve both, ideally. For example, if I were to create a `TwitterReview`, I would expect both the `reviews_count` and `twitter_reviews_count` on a product to go up. Can you just merge them up front inside of `.counter_culture`? Something like:

```ruby
def counter_culture(relation, options = {})
  unless @after_commit_counter_cache
    if superclass.respond_to?(:after_commit_counter_cache) && superclass.after_commit_counter_cache
      @after_commit_counter_cache = superclass.after_commit_counter_cache
    else
      # what was here previously
    end
  end
end
```

Comment (mockdeep) [inline lib/counter_culture.rb]: Actually, now that I think of it, `@@` may not be the solution. I'm not super familiar with how it works, but I think changing it in one place will change it in all the places. So creating a `SimpleReview` will incidentally increment the `twitter_reviews_count`. Not sure, though.

**Comment by magnusvk** [comment]
@mockdeep Can you take another look at this? I expanded the spec a bit to check that subclasses will both inherit their parents counter caches, and at the same time have the ability to have their own, distinct counter caches. I feel significantly better about this approach, and the specs are all green. If you can test whether this fixes your issue and let me know if this passes your smell test, I can probably bake another gem version soon.

File: lib/counter_culture.rb [hunk 3]
```diff
@@ -13,7 +13,13 @@ module ActiveRecord
...
     module ClassMethods
       # this holds all configuration data
-      attr_reader :after_commit_counter_cache
+      def after_commit_counter_cache
+        config = @after_commit_counter_cache || []
+        if superclass.respond_to?(:after_commit_counter_cache) && superclass.after_commit_counter_cache
+          config = superclass.after_commit_counter_cache + config
+        end
+        config
+      end
```
Comment (mockdeep) [inline lib/counter_culture.rb]: Trying to think of a refactor for this. Maybe something like:

```ruby
def after_commit_counter_cache
  Array(@after_commit_counter_cache) + superclass_after_commit_counter_cache
end

private

def superclass_after_commit_counter_cache
  if superclass.respond_to?(:after_commit_counter_cache)
    superclass.after_commit_counter_cache
  else
    []
  end
end
```

**Comment by mockdeep** [comment]
Looks pretty good. I'll try it out a little later today.

File: lib/counter_culture.rb (hunk 3 above)
Comment (mockdeep) [inline lib/counter_culture.rb]: Or:

```ruby
def after_commit_counter_cache
  @after_commit_counter_cache ||= []
  if superclass.respond_to?(:after_commit_counter_cache)
    @after_commit_counter_cache + super
  else
    @after_commit_counter_cache
  end
end
```

**Comment by mockdeep** [comment]
Just tested this out and everything seems to work as expected.

**Comment by jaygen** [comment]
:+1:
