### PR TITLE
Use PaperTrail's new save_with_version when available

### LINKED ISSUE #216: with_papertrail broken when using Papertrail 9x
The behavior of this option and its intent is now broken in Papertrail 9 due to this issue:
https://github.com/airblade/paper_trail/issues/1076

When using the `with_papertrail` option and a change is made which affects a counter_culture model, the model's counted row is *not* updated in the papertrail versions table.

### PR DESCRIPTION
**Pull request by magnusvk**
See https://github.com/airblade/paper_trail/issues/1076

Fixes #216

### CODE REVIEW

**Comment by key88sf** [comment]
👍

File: lib/counter_culture/counter.rb [hunk 1]
```diff
@@ -68,18 +68,19 @@ def change_counter_cache(obj, options)
           klass = relation_klass(relation, source: obj, was: options[:was])
           primary_key = relation_primary_key(relation, source: obj, was: options[:was])
 
+          klass.where(primary_key => id_to_change).update_all updates.join(', ')
```
Comment (key88sf) [inline lib/counter_culture/counter.rb]: @magnusvk I don't think we want to move this before the papertrail call, because that defeats the purpose of creating the version row. It's precisely because the `update_all` does not trigger any version rows to be created which is why we're forcing one before the update happens (in order to record the state of the object before it gets updated).

In our local specs that test this behavior, we compare counted_class.versions.last.object["counted_column_name"] to what it was *before* the update_all.
